expose:
  Args: 
    - --v
    - 4
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded

cleanup:
  Args: 
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
expose:
  config:
    domain: bunnysaber.us-east.containers.appdomain.cloud
    exposer: Ingress
    http: "true"
    tlsacme: "false"
    pathMode: ""
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: registry.ng.bluemix.net
        TILLER_NAMESPACE: kube-system
PipelineSecrets:
  DockerConfig: '{"auths":{"registry.ng.bluemix.net":{"auth":"dG9rZW46ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnFkR2tpT2lJeE1HTmxaakEwT0MwNE16WmlMVFUzT1dRdE9ETTFaUzFsTnpCaE5tVTJOR1UyT1RraUxDSnBjM01pT2lKeVpXZHBjM1J5ZVM1dVp5NWliSFZsYldsNExtNWxkQ0o5LkhZal9odWpWYXk4Xzlmbi1rYXk1aXphaTc0bWE2Z3piaFRNREc0SGs3Mnc="}}}'
